#!/bin/bash
./makefolders.sh
./maketimesyncd.sh
./makekeepalived.sh
./make50-server.sh
./makerabbitmq.sh
./makememcached.sh
./makeetcd.sh
./makeapachekeystone.sh
./makekeystone.sh
./makeglanceapi.sh
./makeplacement.sh
./makeapacheplacment.sh
./makenova.sh
./makeneutron.sh
./makeml2.sh
./makeopenvswitchagent.sh
./makel3agent.sh
./makedhcpagent.sh
