#!/bin/bash
./prepareconfig/makefolders.sh
./prepareconfig/maketimesyncd.sh
./prepareconfig/makekeepalived.sh
./prepareconfig/makehaproxy.sh
./prepareconfig/make50-server.sh
./prepareconfig/makerabbitmq.sh
./prepareconfig/makememcached.sh
./prepareconfig/makeetcd.sh
./prepareconfig/makeapachekeystone.sh
./prepareconfig/makekeystone.sh
./prepareconfig/makeglanceapi.sh
./prepareconfig/makeplacement.sh
./prepareconfig/makeapacheplacment.sh
./prepareconfig/makenova.sh
./prepareconfig/makeneutron.sh
./prepareconfig/makeml2.sh
./prepareconfig/makeopenvswitchagent.sh
./prepareconfig/makel3agent.sh
./prepareconfig/makedhcpagent.sh
./prepareconfig/makemetadataagent.sh
./prepareconfig/makecert.sh
./prepareconfig/makesysctl.sh
./prepareconfig/makeadminopenrc.sh
./prepareconfig/makecinderwsgi.sh
